accounts/urls.py
from django.urls import path

from accounts.views import AccountsLoginView, AccountsLogoutView, signup

urlpatterns = [
    path("signup/", signup, name="signup"),
    path("login/", AccountsLoginView.as_view(), name="login"),
    path("logout/", AccountsLogoutView.as_view(), name="logout"),
]

projects/urls.py
from django.urls import path


from projects.views import (
    ProjectCreateView,
    ProjectListView,
    ProjectDetailView,
)

urlpatterns = [
    path("", ProjectListView.as_view(), name="list_projects"),
    path("<int:pk>/", ProjectDetailView.as_view(), name="show_project"),
    path("create/", ProjectCreateView.as_view(), name="create_project"),
]

tasks/urls.py
from django.urls import path


from tasks.views import (
    TaskCreateView,
    TaskListView,
    TaskUpdateView,
)

urlpatterns = [
    path("create/", TaskCreateView.as_view(), name="create_task"),
    path("mine/", TaskListView.as_view(), name="show_my_tasks"),
    path("<int:pk>/complete/", TaskUpdateView.as_view(), name="complete_task"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("list_projects")),
        name="home",
    ),
    path("accounts/", include("accounts.urls")),
    path("tasks/", include("tasks.urls")),
]

accounts/models.py
# Create your models here.

projects/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL


# Create your models here.
class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    members = models.ManyToManyField(USER_MODEL, related_name="projects")

    def __str__(self):
        return self.name

tasks/models.py
from django.db import models
from django.conf import settings

from projects.models import Project


USER_MODEL = settings.AUTH_USER_MODEL
# Create your models here.


class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateField()
    due_date = models.DateField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        Project, related_name="tasks", on_delete=models.CASCADE
    )
    assignee = models.ForeignKey(
        USER_MODEL, related_name="tasks", null=True, on_delete=models.SET_NULL
    )

    def __str__(self):
        return self.name

accounts/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.models import User

# Create your views here.


class AccountsLoginView(LoginView):
    template_name = "registration/login.html"


class AccountsLogoutView(LogoutView):
    template_name = "registration/logged_out.html"


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            password = request.POST.get("password2")
            user = User.objects.create_user(
                username=username, password=password
            )
            user.save()
            if user is not None:
                login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm(request.POST)
    context = {"form": form}
    return render(request, "registration/signup.html", context)

projects/views.py
from django.shortcuts import redirect
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin

from projects.models import Project

# Create your views here.


class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "projects/list.html"

    def get_queryset(self):
        return Project.objects.filter(members=self.request.user)


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = "projects/detail.html"


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    template_name = "projects/create.html"
    fields = ["name", "description", "members"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.save()
        item.members.add(self.request.user)
        return redirect("show_project", pk=item.pk)

tasks/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from tasks.models import Task


# Create your views here.
class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = "tasks/create.html"
    fields = ["name", "start_date", "due_date", "project", "assignee"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.save()
        return redirect("show_project", pk=item.project.pk)


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "tasks/list.html"

    def get_queryset(self):
        return Task.objects.filter(assignee=self.request.user)


class TaskUpdateView(UpdateView):
    model = Task
    template_name = "tasks/list.html"
    fields = ["is_completed"]
    success_url = reverse_lazy("show_my_tasks")

projects/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <link rel="stylesheet" href="{% static 'css/pretty.css' %}">
    <head>
        <title></title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if request.user.is_authenticated %}
                        <li>
                            <a href="{% url 'show_my_tasks' %}">My records</a>
                        </li>
                        <li>
                            <a href="{% url 'list_projects' %}">My trips</a>
                        </li>
                        <li>
                            <a href="{% url 'logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url 'login' %}">Login</a>
                        </li>
                        <li>
                            <a href="{% url 'signup' %}">Signup</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        {% block content %}
        {% endblock content %}
    </body>
</html>

projects/templates/projects/create.html
{% extends 'base.html' %}
{% block content %}
    <main><br><br><br><br>
        <div class="project-form">
            <h1>Create a new project</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="create">Create</button>
            </form>
        </div>
    </main>
{% endblock content %}

projects/templates/projects/detail.html
{% extends 'base.html' %}
{% load markdownify %}
{% block content %}
    <main><br><br><br><br>
        <div class="project-detail">
            <h1>{{project.name}}</h1>
            <p>{{ project.description|markdownify }}</p>
            <h2>Tasks</h2>
            <p>
                <a href="{% url 'create_task' %}">Create a new task</a>
            </p>
            {% if project.tasks.all %}
                <Table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Start date</th>
                            <th>End date</th>
                            <th>Is completed</th>
                            <tr>
                            </thead>
                            {% for task in project.tasks.all %}
                                <tbody>
                                    <tr>
                                        <td>{{task.name}}</td>
                                        <td>{{task.start_date}}</td>
                                        <td>{{task.due_date}}</td>
                                        <td>{{is_completed}}</td>
                                    </tr>
                                </tbody>
                            {% endfor%}
                        </Table>
            {% else %}
                <p>This project has no tasks</p>
            {% endif %}
        </div>
    </main>
{% endblock content %}

projects/templates/projects/list.html
{% extends 'base.html' %}
{% block content %}
    <main><br><br><br><br>
        <div class="project-list">
            <h1>My Trips</h1>
            <p>
                <a href="{% url 'create_project' %}">Create a new trip</a>
            </p>
            {% if project_list %}
                <Table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Number of records</th>
                        </tr>
                    </thead>
                    {% for project in project_list %}
                    <tbody>
                        <tr>
                            <td><a href="{% url 'show_project' project.pk %}">{{project.name}}</td>
                            <td>{{project.tasks.all|length}}</td>
                        </tr>
                    </tbody>
                            {% endfor%}
                </Table>
            {% else %}
                <p>You are not assigned to any projects</p>
            {% endif %}
        </div>
    </main>
{% endblock content %}

tasks/templates/tasks/create.html
{% extends 'base.html' %}
{% block content %}
    <main><br><br><br><br> 
        <div class="task-form">
            <h1>Create new record</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="create">Create</button>
            </form>
        </div>
    </main>
{% endblock content %}

tasks/templates/tasks/list.html
{% extends 'base.html' %}
{% block content %}
    <main><br><br><br><br>
        <div class="my-tasks-list">
            <h1>My Tasks</h1>
            {% if task_list %}
                <Table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Start date</th>
                            <th>End date</th>
                            <th>Is completed</th>
                            <tr>
                    </thead>
                        <tbody style="text-align:center;">
                            {% for task in task_list %}
                                <tr>
                                    <td>{{task.name}}</td>
                                    <td>{{task.start_date}}</td>
                                    <td>{{task.due_date}}</td>
                                    <td>{{task.is_completed}}</td>
                                        {% if task.is_completed == False %}
                                            <td><form method="post" action="{% url 'complete_task' task.id %}">
                                            {% csrf_token %}
                                                <input type="hidden" name="is_completed" value="True">
                                                <button>Complete</button>
                                            </form></td>
                                    {% endif %}
                                </tr>
                            {% endfor%}
                        </tbody>
                </Table>
            {% else %}
                <p>You have no tasks</p>
            {% endif %}
        </div>
    </main>
{% endblock content %}